backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: "Create {{collection}} “{{slug}}”"
    update: "Update {{collection}} “{{slug}}”"
    delete: "Delete {{collection}} “{{slug}}”"
    uploadMedia: "[skip ci] Upload “{{path}}”"
    deleteMedia: "[skip ci] Delete “{{path}}”"

media_folder: static/img
public_folder: /img

collections:
  - name: "project"
    label: "Project"
    folder: "src/pages/project"
    create: true
    slug: "{{slug}}"
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "project-post",
        }
      - { label: "Project Name", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Youtube link", name: "link", widget: "text", required: false }
      - { label: "Long Description", name: "ld", widget: "markdown" }
      - {
          label: "Available",
          name: "available",
          widget: "boolean",
          default: true,
        }
      - {
          label: "Block Diagram",
          name: "bd",
          widget: "image",
          media_library:
            {
              name: cloudinary,
              config:
                {
                  cloud_name: ddgfeaoyk,
                  api_key: 975543584978688,
                  multiple: false,
                  allow-multiple: false,
                },
            },
        }
      - {
          label: "Pictures",
          name: "pictures",
          widget: image,
          media_library:
            {
              name: cloudinary,
              config:
                {
                  cloud_name: ddgfeaoyk,
                  api_key: 975543584978688,
                  multiple: true,
                  allow-multiple: true,
                },
            },
        }
